### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by juan-g** [akhoury/nodebb-plugin-sanitizehtml#13]
After installing and activating the sanitizehtml plugin, and restarting NodeBB, I click its link on the menu but can't access the configuration page. After reloading on the bowser, it gives this error:
 
```
Internal Error.

Oops! Looks like something went wrong!

/admin/plugins/sanitizehtml

Failed to lookup view "admin/plugins/sanitizehtml" in views directory "/srv/example.com/nodebb/build/public/templates"
```
Tried several times, even reinstalling NodeBB, restarting the server, etc., and the same happens always with this plugin only. NodeBB and the rest of plugins work well.

Please, is there something I can try to fix it? Thank you.

**Comment by akhoury** [comment]
i just pushed a possible fix, try re-installing version `0.2.8` of this plugin, also when you're done, go to the admin dashboard, and click on "REBUILD & RESTART" red button

![screen shot 2018-03-12 at 4 35 26 pm](https://user-images.githubusercontent.com/1398375/37289872-7a5984a2-2613-11e8-97fa-3ac4dddaa820.png)

wait for it to restart then visit http://localhost:4567/admin/plugins/sanitizehtml it should work

**Comment by juan-g** [comment]
Thank you very much. After reinstalling, etc., it works (although for some reason it still says "0.2.7").

I think this plugin can be useful for example to allow safe tags without Markdown equivalent, such as `<center>`. I've just tested it. It's a great plugin. :+1:

By the way, I've seen that NodeBB deactivates possible javascript injections in user's links (Markdown or HTML). That's also great. :+1:

**Comment by akhoury** [comment]
glad i could help
