### ISSUE TITLE
This plugin does not effect in current nodebb release

### ISSUE THREAD

**Issue by gdjam** [akhoury/nodebb-plugin-sanitizehtml#7]
I use this plugin in `NodeBB-1.0.4-auto.6`, i edited some code like `<h1>some header text </h1>` in the default-composer with the default markdown, but the result still show the `<h1>some header text </h1>` not like :

## some header text

**Comment by akhoury** [comment]
did you check the Markdown's "Allow HTML" box?
Go to Admin > Plugins > Markdown and check the Allow HTML if you havent.

https://github.com/akhoury/nodebb-plugin-sanitizehtml#dont-forget-to-shut-off-markdowns-html-sanitize

**Comment by gdjam** [comment]
ok, i have forgot that, thanks so much~
