### ISSUE TITLE
The markdown Blockquote(>) is not effective

### ISSUE THREAD

**Issue by gdjam** [akhoury/nodebb-plugin-sanitizehtml#8]
I have tried the common markdown's element, found that the  Blockquote (>) element is not effective, like:

> the blockquote text

the result still show the `> the blockquote text`

what's the problem ?

**Comment by akhoury** [comment]
i see the problem.

**Comment by akhoury** [comment]
looks like a bug in the https://github.com/punkave/sanitize-html library

I'll do more digging tonight.

## test case
```javascript
var MarkdownIt = require("markdown-it");
var sanitizeHtml = require('sanitize-html');

var m = new MarkdownIt({
    html: true
});

var s1 = sanitizeHtml("> hello");
var s2 = "> hello";


console.log(s1);
console.log(m.render(s1));
console.log('\n---unsanitized--\n');
console.log(s2);
console.log(m.render(s2));
```

## output
```bash
[525] > node temp.js 
&gt; hello
<p>&gt; hello</p>


---unsanitized--

> hello
<blockquote>
<p>hello</p>
</blockquote>
```

**Comment by akhoury** [comment]
hey can you help me test this, try to make this change on your setup, like manually.

https://github.com/akhoury/nodebb-plugin-
sanitizehtml/commit/928c7bfeff4394fd512489d2abe5b12b4066222e

I'm basically making the sanitize occur after the markdown parse, give it a shot, if everything look good, i'll publish the change

**Comment by akhoury** [comment]
revert it, it wont work, i just did https://github.com/akhoury/nodebb-plugin-sanitizehtml/commit/1120291494dcdf1fae913c247b8d70a77a24aef1

**Comment by akhoury** [comment]
ill figure something else tonight

**Comment by akhoury** [comment]
update to nodebb-plugin-sanitizehtml@0.2.5

**Comment by gdjam** [comment]
cool, would you publish to the ACP-Plugin for installation?

**Comment by gdjam** [comment]
ok, i've seen the upgrade~ thanks~
